#设置服务器的端口号
server:
  port: 8081
#数据库连接设置
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.240.93:3306/animail?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.five.animailss.entity
  mapper-locations: classpath:mapper/*.xml

redis:
  host: 47.99.243.62
  port: 6379
  password: 123